name: Publish to PyPI

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+'  # dispara apenas na falta de patch (Z)

jobs:
  build-n-publish-official:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Change package name and remove original script
        run: |
          sed -i '/^sgevalviztest = /d' pyproject.toml

      - name: Prepare pyproject.toml for Test PyPI
        run: |
          sed -i '/^sgevalviztest = "sgevalviz.cli_test:main_wrapper"/d' pyproject.toml

      - name: Build package
        run: |
          rm -rf dist/*
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://pypi.org/legacy/
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
