name: Publish to Test PyPI

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'  # dispara apenas se houver patch (Z)

jobs:
  build-n-publish-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Prepare pyproject.toml for Test PyPI
        run: |
          sed -i 's/^name = "sgevalviz"/name = "sgevalviztest"/' pyproject.toml
          sed -i '/^sgevalviz = /d' pyproject.toml
          sed -i 's/^sgevalviz = /sgevalviztest = /' pyproject.toml

      - name: Build package
        run: |
          rm -rf dist/*
          python -m build

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
